/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonUpload: typeof import('./components/upload/CommonUpload.vue')['default']
    DataTable: typeof import('./components/table/DataTable.vue')['default']
    EducationTypeSelect: typeof import('./components/select/components/EducationTypeSelect.vue')['default']
    EmailInput: typeof import('./components/select/EmailInput.vue')['default']
    HomeHeader: typeof import('./components/layout/HomeHeader.vue')['default']
    IdCardInput: typeof import('./components/select/IdCardInput.vue')['default']
    IfActiveSelect: typeof import('./components/select/IfActiveSelect.vue')['default']
    OperationColumn: typeof import('./components/table/OperationColumn.vue')['default']
    Pagination: typeof import('./components/pagination/Pagination.vue')['default']
    PhoneInput: typeof import('./components/select/PhoneInput.vue')['default']
    PoliticalTypeSelect: typeof import('./components/select/components/PoliticalTypeSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableColumn: typeof import('./components/table/TableColumn.vue')['default']
  }
}
