/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonUpload: typeof import('./components/upload/CommonUpload.vue')['default']
    DataTable: typeof import('./components/table/DataTable.vue')['default']
    EducationTypeSelect: typeof import('./components/select/components/EducationTypeSelect.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmailInput: typeof import('./components/select/EmailInput.vue')['default']
    FlowItem: typeof import('./components/FlowItem.vue')['default']
    FlowItemContainer: typeof import('./components/FlowItemContainer.vue')['default']
    HomeHeader: typeof import('./components/layout/HomeHeader.vue')['default']
    IdCardInput: typeof import('./components/select/IdCardInput.vue')['default']
    IfActiveSelect: typeof import('./components/select/IfActiveSelect.vue')['default']
    OnlineService: typeof import('./components/layout/OnlineService.vue')['default']
    OperationColumn: typeof import('./components/table/OperationColumn.vue')['default']
    Pagination: typeof import('./components/pagination/Pagination.vue')['default']
    PhoneInput: typeof import('./components/select/PhoneInput.vue')['default']
    PoliticalTypeSelect: typeof import('./components/select/components/PoliticalTypeSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableColumn: typeof import('./components/table/TableColumn.vue')['default']
  }
}
